-- CREATE Coupons dimension:

-- Generate Surrogate PK
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_COUPONS;

-- Create Table
CREATE TABLE IF NOT EXISTS BL_DM.DIM_COUPONS (
	COUPON_SURR_ID 	INT 				PRIMARY KEY,
	COUPON_SRC_ID 		VARCHAR(100)	NOT NULL,
	DISCOUNT_SIZE 		VARCHAR(5)		NOT NULL,
	INSERT_DT 			DATE				NOT NULL,
	UPDATE_DT 			DATE				NOT NULL,
	SOURCE_SYSTEM 		VARCHAR(100)	NOT NULL,
	SOURCE_ENTITY 		VARCHAR(100)	NOT NULL
);

-- Associate sequence with the table's surrogate PK
ALTER SEQUENCE BL_DM.SEQ_DIM_COUPONS OWNED BY BL_DM.DIM_COUPONS.COUPON_SURR_ID;

-- Default Row:
INSERT INTO BL_DM.DIM_COUPONS
SELECT -1, 'n.a.', 'n.a.', '1-1-1900'::DATE, '1-1-1900'::DATE, 'MANUAL', 'MANUAL'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.dim_coupons WHERE coupon_surr_id = -1);

COMMIT;