-- CREATE Categories dimension:

-- Generate Surrogate PK
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_CATEGORIES;

-- Create Table
CREATE TABLE IF NOT EXISTS BL_DM.DIM_CATEGORIES (
	CATEGORY_SURR_ID 	INT 				PRIMARY KEY,
	CATEGORY_SRC_ID 	VARCHAR(100)	NOT NULL,
	CATEGORY_NAME 		VARCHAR(100)	NOT NULL,
	INSERT_DT 			DATE				NOT NULL,
	UPDATE_DT 			DATE				NOT NULL,
	SOURCE_SYSTEM 		VARCHAR(100)	NOT NULL,
	SOURCE_ENTITY 		VARCHAR(100)	NOT NULL
);

-- Associate sequence with the table's surrogate PK
ALTER SEQUENCE BL_DM.SEQ_DIM_CATEGORIES OWNED BY BL_DM.DIM_CATEGORIES.CATEGORY_SURR_ID;

-- Default Row:
INSERT INTO BL_DM.DIM_CATEGORIES
SELECT -1, 'n.a.', 'n.a.', '1-1-1900'::DATE, '1-1-1900'::DATE, 'MANUAL', 'MANUAL'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.dim_categories WHERE category_surr_id = -1);

COMMIT;