-- DIM_TIME_DAY DDL
-- Note: it does not require a default row
-- There is no surrogate key.


CREATE TABLE IF NOT EXISTS BL_DM.DIM_TIME_DAY (
  EVENT_DT 					DATE 				PRIMARY KEY,
  EPOCH 						BIGINT 			NOT NULL,
  DAY_NAME 					VARCHAR(20) 	NOT NULL,
  DAY_OF_WEEK 				INT 				NOT NULL,
  IS_WEEKEND 				BOOLEAN 			NOT NULL,
  DAY_OF_MONTH 			INT 				NOT NULL,
  DAY_OF_QUARTER 			INT 				NOT NULL,
  DAY_OF_YEAR 				INT 				NOT NULL,
  WEEK_OF_MONTH 			INT 				NOT NULL,
  WEEK_OF_YEAR 			INT 				NOT NULL,
  WEEK_OF_YEAR_ISO 		VARCHAR(10) 	NOT NULL,
  "MONTH" 					INT 				NOT NULL,
  MONTH_NAME 				VARCHAR(9) 		NOT NULL,
  MONTH_NAME_CUT 			VARCHAR(3) 		NOT NULL,
  "QUARTER" 				INT 				NOT NULL,
  QUARTER_NAME 			VARCHAR(9) 		NOT NULL,
  YEAR_ACTUAL 				INT 				NOT NULL,
  FIRST_DAY_OF_WEEK 		DATE 				NOT NULL,
  LAST_DAY_OF_WEEK 		DATE 				NOT NULL,
  FIRST_DAY_OF_MONTH 	DATE 				NOT NULL,
  LAST_DAY_OF_MONTH 		DATE 				NOT NULL,
  FIRST_DAY_OF_QUARTER 	DATE 				NOT NULL,
  LAST_DAY_OF_QUARTER 	DATE 				NOT NULL,
  FIRST_DAY_OF_YEAR 		DATE 				NOT NULL,
  LAST_DAY_OF_YEAR 		DATE 				NOT NULL,
  MMYYYY 					VARCHAR(6) 		NOT NULL,
  MMDDYYYY 					VARCHAR(10) 	NOT NULL
);