-- CREATE Customers dimension:
-- Note: SCD TYPE 2

-- Generate Surrogate PK
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_CUSTOMERS_SCD;
-- Create Table
CREATE TABLE IF NOT EXISTS BL_DM.DIM_CUSTOMERS_SCD (
	CUSTOMER_SURR_ID 	INT 					PRIMARY KEY,
	CUSTOMER_SRC_ID 	VARCHAR(100)		NOT NULL,
	CUSTOMER_NAME 		VARCHAR(100)		NOT NULL,
	CUSTOMER_GENDER	VARCHAR(10)			NOT NULL,
	CUSTOMER_AGE		SMALLINT				NOT NULL,
	START_DT				DATE					NOT NULL,
	END_DT				DATE					NOT NULL,
	IS_ACTIVE			VARCHAR(1)			NOT NULL,
	INSERT_DT 			DATE					NOT NULL,
	SOURCE_SYSTEM 		VARCHAR(100)		NOT NULL,
	SOURCE_ENTITY 		VARCHAR(100)		NOT NULL
);

-- Associate sequence with the table's surrogate PK
ALTER SEQUENCE BL_DM.SEQ_DIM_CUSTOMERS_SCD OWNED BY BL_DM.DIM_CUSTOMERS_SCD.CUSTOMER_SURR_ID;

-- Default Row:
INSERT INTO BL_DM.DIM_CUSTOMERS_SCD
SELECT -1, 'n.a', 'n.a.', 'n.a.', -1, '31-12-9999'::DATE, '1-1-1900'::DATE, 'Y', '1-1-1900'::DATE,  'MANUAL', 'MANUAL'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.dim_customers_scd WHERE customer_surr_id = -1);

COMMIT;