-- CREATE Payment Methods dimension:

-- Generate Surrogate PK
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_PAYMENT_METHODS;

-- Create Table
CREATE TABLE IF NOT EXISTS BL_DM.DIM_PAYMENT_METHODS (
	PAYMENT_METHOD_SURR_ID 		INT 				PRIMARY KEY,
	PAYMENT_METHOD_SRC_ID 		VARCHAR(100)	NOT NULL,
	PAYMENT_METHOD_NAME	 		VARCHAR(100)	NOT NULL,
	INSERT_DT 						DATE				NOT NULL,
	UPDATE_DT 						DATE				NOT NULL,
	SOURCE_SYSTEM 					VARCHAR(100)	NOT NULL,
	SOURCE_ENTITY 					VARCHAR(100)	NOT NULL
);

-- Associate sequence with the table's surrogate PK
ALTER SEQUENCE BL_DM.SEQ_DIM_PAYMENT_METHODS OWNED BY BL_DM.DIM_PAYMENT_METHODS.PAYMENT_METHOD_SURR_ID;

-- Default Row:
INSERT INTO BL_DM.DIM_PAYMENT_METHODS
SELECT -1, 'n.a.', 'n.a.', '1-1-1900'::DATE, '1-1-1900'::DATE, 'MANUAL', 'MANUAL'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.dim_payment_methods WHERE payment_method_surr_id = -1);

COMMIT;